{
 "title": "Enphase solar panel information",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "device_serial", "query": "label_values(serial_num)" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "expr": "envoy_production_inverters_watt_now",
     "legendFormat": "Produced energy"
    },
    {
     "expr": "envoy_production_inverters_watt_hour_lifetime",
     "legendFormat": "Lifetime production"
    }
   ]
  },
  {
   "title": "Line voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "envoy_relay_rms_voltage",
     "legendFormat": "Line {{line}} voltage {{direction}}"
    },
    {
     "expr": "envoy_relay_rms_voltage{direction=\"production\"} - on(line) envoy_relay_rms_voltage{direction=\"consumption\"}",
     "legendFormat": "Line {{line}} voltage difference"
    }
   ]
  },
  {
   "title": "Detailed summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device statuses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(envoy_device_metadata_info)",
       "legendFormat": "Total devices"
      },
      {
       "expr": "count(envoy_device_communicating == 1)",
       "legendFormat": "Communicating devices"
      },
      { "expr": "sum(envoy_device_operating)", "legendFormat": "Operating devices" },
      { "expr": "sum(envoy_device_producing)", "legendFormat": "Producing devices" },
      { "expr": "sum(envoy_device_provisioned)", "legendFormat": "Provisioned devices" }
     ]
    },
    {
     "title": "Line current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "amp" }
     ],
     "targets": [
      {
       "expr": "envoy_relay_rms_current",
       "legendFormat": "Line {{line}} current {{direction}}"
      }
     ]
    },
    {
     "title": "Envoy request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "envoy_data_request_duration_seconds",
       "legendFormat": "Total request duration"
      },
      {
       "expr": "envoy_inventory_request_duration_seconds",
       "legendFormat": "Inventory request duration"
      },
      {
       "expr": "envoy_production_request_duration_seconds",
       "legendFormat": "Production request duration"
      }
     ]
    },
    {
     "title": "Envoy request failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_inventory_request_failed_count",
       "legendFormat": "Inventory request failed count"
      },
      {
       "expr": "envoy_production_request_failed_count",
       "legendFormat": "Production request failed count"
      }
     ]
    }
   ]
  },
  {
   "title": "Device details ${device_serial}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "device_serial",
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_device_communicating{serial_num=\"$device_serial\"}",
       "legendFormat": "Communicating"
      },
      {
       "expr": "envoy_device_producing{serial_num=\"$device_serial\"}",
       "legendFormat": "Producing"
      },
      {
       "expr": "envoy_device_operating{serial_num=\"$device_serial\"}",
       "legendFormat": "Operating"
      },
      {
       "expr": "envoy_device_provisioned{serial_num=\"$device_serial\"}",
       "legendFormat": "Provisioned"
      }
     ]
    }
   ]
  }
 ]
}